### ISSUE TITLE
The "LinkAssemblies" task failed unexpectedly.

### ISSUE THREAD

**Issue by chennakrishnakasukurthi** [muak/AiForms.Effects#31]
While running in release mode, linking the assemblies am unable to run project with this nuget package.
Can you advice me the fix, for this issue. Pasting error below.

Severity	Code	Description	Project	File	Line	Suppression State
Error		The "LinkAssemblies" task failed unexpectedly.
Mono.Linker.MarkException: Error processing method: 'System.Void AiForms.Effects.Droid.ToFlatButtonPlatformEffect::OnElementPropertyChanged(System.ComponentModel.PropertyChangedEventArgs)' in assembly: 'AiForms.Effects.Droid.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve Xamarin.Forms.BindableProperty Xamarin.Forms.Button::CornerRadiusProperty
   at Mono.Linker.Steps.MarkStep.MarkField(FieldReference reference)
   at Mono.Linker.Steps.MarkStep.MarkInstruction(Instruction instruction)
   at Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
   at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   --- End of inner exception stack trace ---
   at Mono.Linker.Steps.MarkStep.ProcessQueue()System.Void AiForms.Effects.Droid.ToFlatButtonPlatformEffect::OnElementPropertyChanged
   at Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue()
   at Mono.Linker.Steps.MarkStep.Process()
   at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
   at Mono.Linker.Pipeline.Process(LinkContext context)
   at MonoDroid.Tuner.Linker.Process(LinkerOptions options, ILogger logger, LinkContext& context)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	MS.Digital.BOD.Android

**Comment by muak** [comment]
@chennakrishnakasukurthi 

Thank you for your report.

But It is not enough information to survey.
Could you give me more information such as 
AiForms.Effects version, Xamarin.Forms version, Android SDK version, your linker settings and simple code in order to reproduce?

Thank you.

**Comment by chennakrishnakasukurthi** [comment]
Thank you for reply and Help muak.

AiForms.Effects - using the latest stable version
Xamarin.Forms version - 2.5.1.444934

Android SDK version - using latest Oreo (8.1), even i checked by changing  in lower versions as well up to API level 21.

Am attaching a command to StackLayout and its working great in debug mode , while coming to release facing the issue when "**Linking is set to be SDK Assemblies only.**"

Below is sample code.

   <StackLayout Grid.Column="2" ef:AddCommand.On="true" ef:AddCommand.EffectColor="{StaticResource ClickEffectColor}" ef:AddCommand.Command="{Binding SampleCommand}" >
</StackLayout>



Thanks,
Chennakrishna

**Comment by muak** [comment]
@chennakrishnakasukurthi 

Thank you for your additional information.

Though I tried building in the same environment, couldn't reproduce it.
My build worked it without problems.

I'm sorry I couldn't be of any help.

**Comment by chennakrishnakasukurthi** [comment]
@muak 

Thanks for the response and help.

**Comment by jeroen-corteville** [comment]
Hi all, I just ran into this issue, and deleting the /bin & /obj folder for the Android project worked for me.
