### ISSUE TITLE
Crash on Android 4.4 (Java.Lang.NoSuchMethodException)

### ISSUE THREAD

**Issue by gentledepp** [muak/AiForms.Effects#37]
This library has API level 22 set as minimum.
This is absolutely ok, but it would be better if, when used on some minor platform, the app would not crash. 
Other libraries handle this more gracefully by just disabling themselves if the API level is too low. 
So in this case: we would have some ugly buttons, but the app would still work. ;-)

@bruzkovsky - might also be your issue

```

 UNHANDLED EXCEPTION:
11-06 17:50:28.070 I/MonoDroid( 5411): Java.Lang.NoSuchMethodError: no method with name='getStateListAnimator' signature='()Landroid/animation/StateListAnimator;' in class Landroid/view/View;
11-06 17:50:28.070 I/MonoDroid( 5411):   at Java.Interop.JniEnvironment+InstanceMethods.GetMethodID (Java.Interop.JniObjectReference type, System.String name, System.String signature) [0x0005b] in <bea5d01c4e184519b753620a0aaa9c67>:0 
11-06 17:50:28.070 I/MonoDroid( 5411):   at Java.Interop.JniType.GetInstanceMethod (System.String name, System.String signature) [0x0000c] in <bea5d01c4e184519b753620a0aaa9c67>:0 
11-06 17:50:28.070 I/MonoDroid( 5411):   at Java.Interop.JniPeerMembers+JniInstanceMethods.GetMethodInfo (System.String encodedMember) [0x00031] in <bea5d01c4e184519b753620a0aaa9c67>:0 
11-06 17:50:28.070 I/MonoDroid( 5411):   at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualObjectMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0001c] in <bea5d01c4e184519b753620a0aaa9c67>:0 
11-06 17:50:28.070 I/MonoDroid( 5411):   at Android.Views.View.get_StateListAnimator () [0x0000a] in <e88bfb514a2a435cb900154e4ab621e8>:0 
11-06 17:50:28.070 I/MonoDroid( 5411):   at AiForms.Effects.Droid.ToFlatButtonPlatformEffect.OnAttached () [0x0003c] in <941053be526a4482b8e4d919d9699326>:0 
11-06 17:50:28.070 I/MonoDroid( 5411):   at Xamarin.Forms.Effect.SendAttached () [0x00009] in D:\a\1\s\Xamarin.Forms.Core\Effect.cs:54 
11-06 17:50:28.070 I/MonoDroid( 5411):   at Xamarin.Forms.RoutingEffect.SendAttached () [0x00000] in D:\a\1\s\Xamarin.Forms.Core\RoutingEffect.cs:29 
11-06 17:50:28.070 I/MonoDroid( 5411):   at Xamarin.Forms.Element.AttachEffect (Xamarin.Forms.Effect effect) [0x00045] in D:\a\1\s\Xamarin.Forms.Core\Element.cs:538 
11-06 17:50:28.070 I/MonoDroid( 5411):   at Xamarin.Forms.Element.set_EffectControlProvider (Xamarin.Forms.IEffectControlProvider value) [0x0007c] in D:\a\1\s\Xamarin.Forms.Core\Element.cs:256 
11-06 17:50:28.070 I/MonoDroid( 5411):   at Xamarin.Forms.Internals.EffectUtilities.RegisterEffectControlProvider (Xamarin.Forms.IEffectControlProvider self, Xamarin.Forms.IElementController oldElement, Xamarin.Forms.IElementController newElement) [0x0001a] in D:\a\1\s\Xamarin.Forms.Core\Internals\EffectUtilities.cs:16 
11-06 17:50:28.070 I/MonoDroid( 5411):   at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].SetElement (TElement element) [0x00130] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:222 
11-06 17:50:28.070 I/MonoDroid( 5411):   at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].Xamarin.Forms.Platform.Android.IVisualElementRenderer.SetElement (Xamarin.Forms.VisualElement element) [0x00027] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:125 
In mgmain JNI_OnLoad11-06 17:50:28.070 I/MonoDroid( 5411):   at Xamarin.Forms.Platform.Android.Platform.CreateRenderer (Xamarin.Forms.VisualElement element, Android.Content.Context context) [0x0001f] in D:\a\1\s\Xamarin.Forms.Platform.Android\Platform.cs:330 

11-06 17:50:28.070 I/MonoDroid( 5411):   at Xamarin.Forms.Platform.Android.VisualElementPackager.AddChild (Xamarin.Forms.VisualElement view, Xamarin.Forms.Platform.Android.IVisualElementRenderer oldRenderer, Xamarin.Forms.Platform.Android.RendererPool pool, System.Boolean sameChildren) [0x000af] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:120 
11-06 17:50:28.070 I/MonoDroid( 5411):   at Xamarin.Forms.Platform.Android.VisualElementPackager.SetElement (Xamarin.Forms.VisualElement oldElement, Xamarin.Forms.VisualElement newElement) [0x00139] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:268 
11-06 17:50:28.070 I/MonoDroid( 5411):   at Xamarin.Forms.Platform.Android.VisualElementPackager.Load () [0x00000] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:92 
11-06 17:50:28.070 I/MonoDroid( 5411):   at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].SetPackager (Xamarin.Forms.Platform.Android.VisualElementPackager packager) [0x00007] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:389 
11-06 17:50:28.070 I/MonoDroid( 5411):   at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].SetElement (TElement element) [0x000f2] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:214 
11-06 17:50:28.070 I/MonoDroid( 5411):   at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].Xamarin.Forms.Platform.Android.IVisualElementRenderer.SetElement (Xamarin.Forms.VisualElement element) [0x00027] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:125 
11-06 17:50:28.070 I/MonoDroid( 5411):   at Xamarin.Forms.Platform.Android.Platform.CreateRenderer (Xamarin.Forms.VisualElement element, Android.Content.Context context) [0x0001f] in D:\a\1\s\Xamarin.Forms.Platform.Android\Platform.cs:330 
11-06 17:50:28.070 I/MonoDroid( 5411):   at Xamarin.Forms.Platform.Android.VisualElementPackager.AddChild (Xamarin.Forms.VisualElement view, Xamarin.Forms.Platform.Android.IVisualElementRenderer oldRenderer, Xamarin.Forms.Platform.Android.RendererPool pool, System.Boolean sameChildren) [0x000af] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:120 
11-06 17:50:28.070 I/MonoDroid( 5411):   at Xamarin.Forms.Platform.Android.VisualElementPackager.SetElement (Xamarin.Forms.VisualElement oldElement, Xamarin.Forms.VisualElement newElement) [0x00139] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:268 
11-06 17:50:28.070 I/MonoDroid( 5411):   at Xamarin.Forms.Platform.Android.VisualElementPackager.Load () [0x00000] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:92 
11-06 17:50:28.070 I/MonoDroid( 5411):   at Xamarin.Forms.Platform.Android.FastRenderers.FrameRenderer.OnElementChanged (Xamarin.Forms.Platform.Android.ElementChangedEventArgs`1[TElement] e) [0x00098] in D:\a\1\s\Xamarin.Forms.Platform.Android\FastRenderers\FrameRenderer.cs:184 
11-06 17:50:28.070 I/MonoDroid( 5411):   at Xamarin.Forms.Platform.Android.FastRenderers.FrameRenderer.set_Element (Xamarin.Forms.Frame value) [0x00018] in D:\a\1\s\Xamarin.Forms.Platform.Android\FastRenderers\FrameRenderer.cs:61 
11-06 17:50:28.070 I/MonoDroid( 5411):   at Xamarin.Forms.Platform.Android.FastRenderers.FrameRenderer.Xamarin.Forms.Platform.Android.IVisualElementRenderer.SetElement (Xamarin.Forms.VisualElement element) [0x00015] in D:\a\1\s\Xamarin.Forms.Platform.Android\FastRenderers\FrameRenderer.cs:82 
11-06 17:50:28.070 I/MonoDroid( 5411):   at Xamarin.Forms.Platform.Android.Platform.CreateRenderer (Xamarin.Forms.VisualElement element, Android.Content.Context context) [0x0001f] in D:\a\1\s\Xamarin.Forms.Platform.Android\Platform.cs:330 
11-06 17:50:28.075 I/MonoDroid( 5411):   at Xamarin.Forms.Platform.Android.ViewCellRenderer.GetCellCore (Xamarin.Forms.Cell item, Android.Views.View convertView, Android.Views.ViewGroup parent, Android.Content.Context context) [0x0008f] in D:\a\1\s\Xamarin.Forms.Platform.Android\Cells\ViewCellRenderer.cs:41 
11-06 17:50:28.075 I/MonoDroid( 5411):   at Xamarin.Forms.Platform.Android.CellRenderer.GetCell (Xamarin.Forms.Cell item, Android.Views.View convertView, Android.Views.ViewGroup parent, Android.Content.Context context) [0x00075] in D:\a\1\s\Xamarin.Forms.Platform.Android\Cells\CellRenderer.cs:51 
11-06 17:50:28.075 I/MonoDroid( 5411):   at Xamarin.Forms.Platform.Android.CellFactory.GetCell (Xamarin.Forms.Cell item, Android.Views.View convertView, Android.Views.ViewGroup parent, Android.Content.Context context, Xamarin.Forms.View view) [0x0001e] in D:\a\1\s\Xamarin.Forms.Platform.Android\Cells\CellFactory.cs:20 
11-06 17:50:28.075 I/MonoDroid( 5411):   at Xamarin.Forms.Platform.Android.ListViewAdapter.GetView (System.Int32 position, Android.Views.View convertView, Android.Views.ViewGroup parent) [0x00200] in D:\a\1\s\Xamarin.Forms.Platform.Android\Renderers\ListViewAdapter.cs:298 
11-06 17:50:28.075 I/MonoDroid( 5411):   at Android.Widget.BaseAdapter.n_GetView_ILandroid_view_View_Landroid_view_ViewGroup_ (System.IntPtr jnienv, System.IntPtr native__this, System.Int32 position, System.IntPtr native_convertView, System.IntPtr native_parent) [0x0001a] in <e88bfb514a2a435cb900154e4ab621e8>:0 
11-06 17:50:28.075 I/MonoDroid( 5411):   at (wrapper dynamic-method) System.Object.98(intptr,intptr,int,intptr,intptr)
11-06 17:50:28.075 I/MonoDroid( 5411):   --- End of managed Java.Lang.NoSuchMethodError stack trace ---
11-06 17:50:28.075 I/MonoDroid( 5411): java.lang.NoSuchMethodError: no method with name='getStateListAnimator' signature='()Landroid/animation/StateListAnimator;' in class Landroid/view/View;
11-06 17:50:28.075 I/MonoDroid( 5411): 	at md51558244f76c53b6aeda52c8a337f2c37.ListViewAdapter.n_getView(Native Method)
11-06 17:50:28.075 I/MonoDroid( 5411): 	at md51558244f76c53b6aeda52c8a337f2c37.ListViewAdapter.getView(ListViewAdapter.java:100)
11-06 17:50:28.075 I/MonoDroid( 5411): 	at android.widget.HeaderViewListAdapter.getView(HeaderViewListAdapter.java:230)
11-06 17:50:28.075 I/MonoDroid( 5411): 	at android.widget.AbsListView.obtainView(AbsListView.java:2305)
11-06 17:50:28.075 I/MonoDroid( 5411): 	at android.widget.ListView.makeAndAddView(ListView.java:1794)
11-06 17:50:28.075 I/MonoDroid( 5411): 	at android.widget.ListView.fillDown(ListView.java:695)
11-06 17:50:28.075 I/MonoDroid( 5411): 	at android.widget.ListView.fillFromTop(ListView.java:756)
11-06 17:50:28.075 I/MonoDroid( 5411): 	at android.widget.ListView.layoutChildren(ListView.java:1634)
11-06 17:50:28.075 I/MonoDroid( 5411): 	at android.widget.AbsListView.onLayout(AbsListView.java:2129)
11-06 17:50:28.075 I/MonoDroid( 5411): 	at android.view.View.layout(View.java:14873)
11-06 17:50:28.075 I/MonoDroid( 5411): 	at android.view.ViewGroup.layout(ViewGroup.java:4651)
11-06 17:50:28.075 I/MonoDroid( 5411): 	at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:611)
11-06 17:50:28.075 I/MonoDroid( 5411): 	at android.view.View.layout(View.java:14873)
11-06 17:50:28.075 I/MonoDroid( 5411): 	at android.view.ViewGroup.layout(ViewGroup.java:4651)
11-06 17:50:28.075 I/MonoDroid( 5411): 	at md51558244f76c53b6aeda52c8a337f2c37.ListViewRenderer.n_onLayout(Native Method)
11-06 17:50:28.075 I/MonoDroid( 5411): 	at md51558244f76c53b6aeda52c8a337f2c37.ListViewRenderer.onLayout(ListViewRenderer.java:65)
11-06 17:50:28.075 I/MonoDroid( 5411): 	at android.view.View.layout(View.java:14873)
11-06 17:50:28.075 I/MonoDroid( 5411): 	at android.view.ViewGroup.layout(ViewGroup.java:4651)
11-06 17:50:28.075 I/MonoDroid( 5411): 	at com.xamarin.forms.platform.android.FormsViewGroup.measureAndLayout(FormsViewGroup.java:37)
11-06 17:50:28.075 I/MonoDroid( 5411): 	at md51558244f76c53b6aeda52c8a337f2c37.VisualElementRenderer_1.n_onLayout(Native Method)
11-06 17:50:28.075 I/MonoDroid( 5411): 	at md51558244f76c53b6aeda52c8a337f2c37.VisualElementRenderer_1.onLayout(VisualElementRenderer_1.java:81)
11-06 17:50:28.075 I/MonoDroid( 5411): 	at android.view.View.layout(View.java:14873)
11-06 17:50:28.075 I/MonoDroid( 5411): 	at android.view.ViewGroup.layout(ViewGroup.java:4651)
11-06 17:50:28.075 I/MonoDroid( 5411): 	at com.xamarin.forms.platform.android.FormsViewGroup.measureAndLayout(FormsViewGroup.java:37)
11-06 17:50:28.075 I/MonoDroid( 5411): 	at md58432a647068b097f9637064b8985a5e0.NavigationPageRenderer.n_onLayout(Native Method)
11-06 17:50:28.075 I/MonoDroid( 5411): 	at md58432a647068b097f9637064b8985a5e0.NavigationPageRenderer.onLayout(NavigationPageRenderer.java:65)
11-06 17:50:28.075 I/MonoDroid( 5411): 	at android.view.View.layout(View.java:14873)
11-06 17:50:28.075 I/MonoDroid( 5411): 	at android.view.ViewGroup.layout(ViewGroup.java:4651)
11-06 17:50:28.075 I/MonoDroid( 5411): 	at com.xamarin.forms.platform.android.FormsViewGroup.measureAndLayout(FormsViewGroup.java:37)
11-06 17:50:28.075 I/MonoDroid( 5411): 	at md58432a647068b097f9637064b8985a5e0.MasterDetailContainer.n_onLayout(Native Method)
11-06 17:50:28.075 I/MonoDroid( 5411): 	at md58432a647068b097f9637064b8985a5e0.MasterDetailContainer.onLayout(MasterDetailContainer.java:45)
11-06 17:50:28.075 I/MonoDroid( 5411): 	at android.view.View.layout(View.java:14873)
11-06 17:50:28.075 I/MonoDroid( 5411): 	at android.view.ViewGroup.layout(ViewGroup.java:4651)
11-06 17:50:28.075 I/MonoDroid( 5411): 	at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1172)
11-06 17:50:28.075 I/MonoDroid( 5411): 	at md58432a647068b097f9637064b8985a5e0.MasterDetailPageRenderer.n_onLayout(Native Method)
11-06 17:50:28.075 I/MonoDroid( 5411): 	at md58432a647068b097f9637064b8985a5e0.MasterDetailPageRenderer.onLayout(MasterDetailPageRenderer.java:68)
11-06 17:50:28.075 I/MonoDroid( 5411): 	at android.view.View.layout(View.java:14873)
11-06 17:50:28.075 I/MonoDroid( 5411): 	at android.view.ViewGroup.layout(ViewGroup.java:4651)
11-06 17:50:28.075 I/MonoDroid( 5411): 	at md58432a647068b097f9637064b8985a5e0.Platform_ModalContainer.n_onLayout(Native Method)
11-06 17:50:28.075 I/MonoDroid( 5411): 	at md58432a647068b097f9637064b8985a5e0.Platform_ModalContainer.onLayout(Platform_ModalContainer.java:45)
11-06 17:50:28.075 I/MonoDroid( 5411): 	at android.view.View.layout(View.java:14873)
11-06 17:50:28.075 I/MonoDroid( 5411): 	at android.view.ViewGroup.layout(ViewGroup.java:4651)
11-06 17:50:28.075 I/MonoDroid( 5411): 	at md51558244f76c53b6aeda52c8a337f2c37.PlatformRenderer.n_onLayout(Native Method)
11-06 17:50:28.075 I/MonoDroid( 5411): 	at md51558244f76c53b6aeda52c8a337f2c37.PlatformRenderer.onLayout(PlatformRenderer.java:55)
11-06 17:50:28.075 I/MonoDroid( 5411): 	at android.view.View.layout(View.java:14873)
11-06 17:50:28.075 I/MonoDroid( 5411): 	at android.view.ViewGroup.layout(ViewGroup.java:4651)
11-06 17:50:28.075 I/MonoDroid( 5411): 	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1055)
11-06 17:50:28.075 I/MonoDroid( 5411): 	at android.view.View.layout(View.java:14873)
11-06 17:50:28.075 I/MonoDroid( 5411): 	at android.view.ViewGroup.layout(ViewGroup.java:4651)
11-06 17:50:28.075 I/MonoDroid( 5411): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
11-06 17:50:28.075 I/MonoDroid( 5411): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
11-06 17:50:28.075 I/MonoDroid( 5411): 	at android.view.View.layout(View.java:14873)
11-06 17:50:28.075 I/MonoDroid( 5411): 	at android.view.ViewGroup.layout(ViewGroup.java:4651)
11-06 17:50:28.075 I/MonoDroid( 5411): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
11-06 17:50:28.075 I/MonoDroid( 5411): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
11-06 17:50:28.075 I/MonoDroid( 5411): 	at android.view.View.layout(View.java:14873)
11-06 17:50:28.075 I/MonoDroid( 5411): 	at android.view.ViewGroup.layout(ViewGroup.java:4651)
11-06 17:50:28.075 I/MonoDroid( 5411): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
11-06 17:50:28.075 I/MonoDroid( 5411): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
11-06 17:50:28.075 I/MonoDroid( 5411): 	at android.view.View.layout(View.java:14873)
11-06 17:50:28.075 I/MonoDroid( 5411): 	at android.view.ViewGroup.layout(ViewGroup.java:4651)
11-06 17:50:28.075 I/MonoDroid( 5411): 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1697)
11-06 17:50:28.075 I/MonoDroid( 5411): 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1551)
11-06 17:50:28.075 I/MonoDroid( 5411): 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1460)
11-06 17:50:28.075 I/MonoDroid( 5411): 	at android.view.View.layout(View.java:14873)
11-06 17:50:28.075 I/MonoDroid( 5411): 	at android.view.ViewGroup.layout(ViewGroup.java:4651)
11-06 17:50:28.075 I/MonoDroid( 5411): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
11-06 17:50:28.075 I/MonoDroid( 5411): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
11-06 17:50:28.075 I/MonoDroid( 5411): 	at android.view.View.layout(View.java:14873)
11-06 17:50:28.075 I/MonoDroid( 5411): 	at android.view.ViewGroup.layout(ViewGroup.java:4651)
11-06 17:50:28.075 I/MonoDroid( 5411): 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2061)
11-06 17:50:28.075 I/MonoDroid( 5411): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1815)
11-06 17:50:28.075 I/MonoDroid( 5411): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1042)
11-06 17:50:28.075 I/MonoDroid( 5411): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5905)
11-06 17:50:28.075 I/MonoDroid( 5411): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:780)
11-06 17:50:28.075 I/MonoDroid( 5411): 	at android.view.Choreographer.doCallbacks(Choreographer.java:593)
11-06 17:50:28.075 I/MonoDroid( 5411): 	at android.view.Choreographer.doFrame(Choreographer.java:562)
11-06 17:50:28.075 I/MonoDroid( 5411): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:766)
11-06 17:50:28.075 I/MonoDroid( 5411): 	at android.os.Handler.handleCallback(Handler.java:733)
11-06 17:50:28.075 I/MonoDroid( 5411): 	at android.os.Handler.dispatchMessage(Handler.java:95)
11-06 17:50:28.075 I/MonoDroid( 5411): 	at android.os.Looper.loop(Looper.java:136)
11-06 17:50:28.075 I/MonoDroid( 5411): 	at android.app.ActivityThread.main(ActivityThread.java:5314)
11-06 17:50:28.075 I/MonoDroid( 5411): 	at java.lang.reflect.Method.invokeNative(Native Method)
11-06 17:50:28.075 I/MonoDroid( 5411): 	at java.lang.reflect.Method.invoke(Method.java:515)
11-06 17:50:28.075 I/MonoDroid( 5411): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:864)
11-06 17:50:28.075 I/MonoDroid( 5411): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:680)
11-06 17:50:28.075 I/MonoDroid( 5411): 	at dalvik.system.NativeStart.main(Native Method)
11-06 17:50:28.125 W/dalvikvm( 5411): JNI WARNING: JNI function CallObjectMethodA called with exception pending
11-06 17:50:28.125 W/dalvikvm( 5411):              in Lmd51558244f76c53b6aeda52c8a337f2c37/ListViewAdapter;.n_getView:(ILandroid/view/View;Landroid/view/ViewGroup;)Landroid/view/View; (CallObjectMethodA)
```

**Comment by muak** [comment]
@gentledepp 

Thank you for your advice.
For now, there isn't a plan to implement it, but I will think about its implementation.

**Comment by gentledepp** [comment]
I did not mean to patronize you - maybe I will be able to do a PR soon ;-)
It is just hard to compile the development branch as it requires a prerelease package of AiForms.SettingsView.

**Comment by muak** [comment]
@gentledepp 

Thank you for your PR😄
I will review it.

**Comment by muak** [comment]
@gentledepp 

I merged it into the development branch.
For the master branch, I will merge it when the next stable version is released.

Thank you.
